#!/bin/bash -xv

HOST_NAME=cdh00
HOST_IP=172.27.4.12
GATEWAY=172.27.0.1
ISO_PATH=/root/iso
VOLUME_PATH=/home/whwstar/volume/$HOST_NAME
image=4paradigm/centos:7.2

if [ `docker ps -a | grep $HOST_NAME | wc -l` -eq 0 ];then
    mkdir -p $VOLUME_PATH
    docker run -itd -h $HOST_NAME --name=$HOST_NAME --net=none -v $ISO_PATH:$ISO_PATH  $image /bin/bash
    pipework br0 $HOST_NAME $HOST_IP/20@$GATEWAY
    docker exec -d $HOST_NAME /usr/sbin/sshd -D
elif [ `docker ps -a | grep prophet-01 | wc -l` -eq 1 ];then
    docker start $HOST_NAME
    pipework br0 $HOST_NAME $HOST_IP/20@$GATEWAY
    docker exec -d $HOST_NAME /usr/sbin/sshd -D
else
    echo "docker start exception"
